palette = 0=#34383c
palette = 1=#e46c75
palette = 2=#98c379
palette = 3=#e0af68
palette = 4=#81a5dd
palette = 5=#c6a0f6
palette = 6=#6cc6c8
palette = 7=#d8dee9

palette = 8=#4c5054
palette = 9=#ed747f
palette = 10=#a6d189
palette = 11=#e9b97a
palette = 12=#8db1ec
palette = 13=#d2acff
palette = 14=#79d2d4
palette = 15=#ebf1fa

background = #24282c
foreground = #d8dee9

cursor-color = #d8dee9
cursor-text = #24282c

selection-background = #2f3236
selection-foreground = #d8dee9
