palette = 0=#1f1d2e
palette = 1=#eb6f92
palette = 2=#31748f
palette = 3=#f6c177
palette = 4=#9ccfd8
palette = 5=#c4a7e7
palette = 6=#9ccfd8
palette = 7=#e0def4

palette = 8=#6e6a86
palette = 9=#eb6f92
palette = 10=#9ccfd8
palette = 11=#f0d1ab
palette = 12=#b1e0ea
palette = 13=#dabfff
palette = 14=#9ccfd8
palette = 15=#f2f0ff

background = 191724
foreground = e0def4

cursor-color = ebbebe
cursor-text = 191724

selection-background = 2a2837
selection-foreground = e0def4
