palette = 0=#000000
palette = 1=#555555
palette = 2=#777777
palette = 3=#999999
palette = 4=#bbbbbb
palette = 5=#dddddd
palette = 6=#888888
palette = 7=#ffffff

palette = 8=#222222
palette = 9=#777777
palette = 10=#999999
palette = 11=#bbbbbb
palette = 12=#dddddd
palette = 13=#f2f2f2
palette = 14=#cccccc
palette = 15=#ffffff

background = 000000
foreground = ffffff

cursor-color = ffffff
cursor-text = 000000

selection-background = 222222
selection-foreground = ffffff
