# Importing Colors
source = $HOME/.config/hypr/colors/colors.conf

# Importing the other modules
source = $HOME/.config/hypr/modules/general.conf
source = $HOME/.config/hypr/modules/binds.conf
source = $HOME/.config/hypr/modules/theming.conf
source = $HOME/.config/hypr/modules/input.conf
source = $HOME/.config/hypr/modules/autostart.conf
source = $HOME/.config/hypr/modules/windowrules.conf
source = $HOME/.config/hypr/modules/looknfeel.conf
source = $HOME/.config/hypr/modules/environments.conf
