require("modules.monitors")
require("modules.autostart")
require("modules.environments")
require("modules.looknfeel")
require("modules.windowrules")
require("modules.theming")
require("modules.input")
require("modules.binds")
