-- local M = {}
--
-- local colors = {
-- 	-- base
-- 	bgd = "#111111",
-- 	bg = "#1c1c1c",
-- 	fg = "#e6e6e6",
-- 	white = "#f2f2f2",
-- 	bwhite = "#ffffff",
--
-- 	-- grays (derived from black/bright_black)
-- 	black = "#2a2a2a",
-- 	bblack = "#4a4a4a",
-- 	mid = "#3a3a3a", -- interpolated midpoint
--
-- 	-- pastel accents
-- 	red = "#d8b4b4",
-- 	lred = "#e8c8c8",
-- 	green = "#c4d6c4",
-- 	lgreen = "#d8e6d8",
-- 	yellow = "#ded8b8",
-- 	lyellow = "#eeeac9",
-- 	blue = "#c3cadd",
-- 	lblue = "#d5daf1",
-- 	magenta = "#dac3dd",
-- 	lmagenta = "#e8d5f1",
-- 	cyan = "#c3dedd",
-- 	lcyan = "#d5f0f0",
-- 	orange = "#f7dcc6",
-- }
--
-- function M.colorscheme()
-- 	vim.cmd("highlight clear")
-- 	vim.cmd("syntax reset")
--
-- 	vim.o.background = "dark"
-- 	vim.g.colors_name = "mono"
--
-- 	local set = vim.api.nvim_set_hl
--
-- 	-- ui (transparent bg = no bg field on Normal)
-- 	set(0, "Normal", { fg = colors.fg })
-- 	set(0, "NormalFloat", { fg = colors.fg, bg = colors.bgd })
-- 	set(0, "FloatBorder", { fg = colors.bblack, bg = colors.bgd })
-- 	set(0, "CursorLine", { bg = colors.black })
-- 	set(0, "Visual", { bg = colors.mid })
-- 	set(0, "Search", { fg = colors.bgd, bg = colors.yellow })
-- 	set(0, "IncSearch", { fg = colors.bgd, bg = colors.orange })
-- 	set(0, "StatusLine", { bg = colors.black })
-- 	set(0, "StatusLineNC", { bg = colors.bgd })
-- 	set(0, "VertSplit", { fg = colors.bblack })
-- 	set(0, "WinSeparator", { fg = colors.bblack })
-- 	set(0, "LineNr", { fg = colors.bblack })
-- 	set(0, "CursorLineNr", { fg = colors.orange, bold = true })
-- 	set(0, "SignColumn", {}) -- transparent
-- 	set(0, "Folded", { fg = colors.bblack, bg = colors.black })
--
-- 	-- popup
-- 	set(0, "Pmenu", { fg = colors.fg, bg = colors.black })
-- 	set(0, "PmenuSel", { fg = colors.bgd, bg = colors.blue })
-- 	set(0, "PmenuSbar", { bg = colors.black })
-- 	set(0, "PmenuThumb", { bg = colors.bblack })
--
-- 	-- syntax
-- 	set(0, "Comment", { fg = colors.bblack, italic = true })
-- 	set(0, "Constant", { fg = colors.magenta })
-- 	set(0, "String", { fg = colors.green })
-- 	set(0, "Identifier", { fg = colors.blue })
-- 	set(0, "Function", { fg = colors.yellow })
-- 	set(0, "Statement", { fg = colors.red })
-- 	set(0, "Type", { fg = colors.cyan, bold = true })
-- 	set(0, "Special", { fg = colors.orange })
-- 	set(0, "Error", { fg = colors.lred, bold = true })
-- 	set(0, "Keyword", { fg = colors.red })
-- 	set(0, "Variable", { fg = colors.fg })
-- 	set(0, "@keyword", { fg = colors.red })
-- 	set(0, "@function", { fg = colors.yellow })
-- 	set(0, "@variable", { fg = colors.fg })
-- 	set(0, "@type", { fg = colors.cyan })
--
-- 	-- blink
-- 	set(0, "BlinkCmpMenu", { bg = colors.bgd })
-- 	set(0, "BlinkCmpMenuBorder", { fg = colors.bblack, bg = colors.bgd })
-- 	set(0, "BlinkCmpMenuSelection", { fg = colors.bgd, bg = colors.blue })
-- 	set(0, "BlinkCmpLabel", { fg = colors.fg })
-- 	set(0, "BlinkCmpLabelDetail", { fg = colors.bblack })
-- 	set(0, "BlinkCmpLabelDescription", { fg = colors.bblack })
-- 	set(0, "BlinkCmpLabelMatch", { fg = colors.orange, bold = true })
-- 	set(0, "BlinkCmpKind", { fg = colors.cyan })
-- 	set(0, "BlinkCmpDoc", { fg = colors.fg, bg = colors.black })
-- 	set(0, "BlinkCmpDocBorder", { fg = colors.bblack, bg = colors.black })
--
-- 	-- oil.nvim
-- 	set(0, "OilDir", { fg = colors.blue, bold = true })
-- 	set(0, "OilDirIcon", { fg = colors.blue })
-- 	set(0, "OilFile", { fg = colors.fg })
-- 	set(0, "OilFileIcon", { fg = colors.fg })
-- 	set(0, "OilLink", { fg = colors.cyan })
-- 	set(0, "OilLinkTarget", { fg = colors.cyan, italic = true })
-- 	set(0, "OilOrphanLink", { fg = colors.red })
-- 	set(0, "OilSocket", { fg = colors.magenta })
-- 	set(0, "OilPipe", { fg = colors.yellow })
-- 	set(0, "OilExecutable", { fg = colors.green })
-- 	set(0, "OilRestore", { fg = colors.yellow })
-- 	set(0, "OilCreate", { fg = colors.green })
-- 	set(0, "OilDelete", { fg = colors.red })
-- 	set(0, "OilMove", { fg = colors.orange })
-- 	set(0, "OilCopy", { fg = colors.lcyan })
-- 	set(0, "OilChange", { fg = colors.yellow })
--
--   -- Markdown / Org
--   set(0, "@markup.link", { fg = colors.blue, underline = true, })
--   set(0, "@markup.link.label", { fg = colors.blue, })
--   set(0, "@markup.link.url", { fg = colors.cyan, underline = true, })
--   set(0, "@markup.raw", { fg = colors.green, })
--   set(0, "@markup.quote", { fg = colors.bblack, italic = true, })
--   set(0, "@markup.list", { fg = colors.orange, })
--   set(0, "@markup.list.checked", { fg = colors.green, })
--   set(0, "@markup.list.unchecked", { fg = colors.yellow, })
--   set(0, "markdownBold", { bold = true })
--   set(0, "markdownItalic", { italic = true })
--   set(0, "markdownStrike", { strikethrough = true })
--   set(0, "markdownCodeBlock", { fg = colors.green })
--   set(0, "markdownOrderedListMarker", { fg = colors.orange, bold = true })
--   set(0, "@markup.heading.1", { fg = colors.orange, bold = true })
--   set(0, "@markup.heading.2", { fg = colors.yellow, bold = true })
--   set(0, "@markup.heading.3", { fg = colors.green, bold = true })
--   set(0, "@markup.heading.4", { fg = colors.blue, bold = true })
--   set(0, "@markup.heading.5", { fg = colors.magenta, bold = true })
--   set(0, "@markup.heading.6", { fg = colors.cyan, bold = true })
--
--   -- Obsidian
--   set(0, "ObsidianTodo", { fg = colors.yellow, bold = true, })
--   set(0, "ObsidianDone", { fg = colors.green, bold = true, })
--   set(0, "ObsidianRightArrow", { fg = colors.blue, })
--   set(0, "ObsidianTilde", { fg = colors.orange, })
--   set(0, "ObsidianBullet", { fg = colors.orange, })
--   set(0, "ObsidianTag", { fg = colors.magenta, })
--   set(0, "ObsidianRefText", { fg = colors.blue, underline = true, })
--   set(0, "ObsidianExtLinkIcon", { fg = colors.cyan, })
--   set(0, "ObsidianHighlightText", { bg = colors.yellow, fg = colors.bgd, })
--
-- 	if package.loaded["lualine"] then
-- 		require("lualine").setup({
-- 			options = { theme = "auto" },
-- 		})
-- 	end
-- end
--
-- return M

require('tokyonight').setup({
  transparent = true
})
vim.cmd("colorscheme tokyonight-storm")

