$bg = rgba(282a36ff)
$fg = rgba(f8f8f2ff)

$black = rgba(21222cff)
$red = rgba(ff5555ff)
$green = rgba(50fa7bff)
$yellow = rgba(f1fa8cff)
$blue = rgba(bd93f9ff)
$magenta = rgba(ff79c6ff)
$cyan = rgba(8be9fdff)
$white = rgba(f8f8f2ff)

$bright_black = rgba(6272a4ff)
$bright_red = rgba(ff6e6eff)
$bright_green = rgba(69ff94ff)
$bright_yellow = rgba(ffffa5ff)
$bright_blue = rgba(d6acffff)
$bright_magenta = rgba(ff92d0ff)
$bright_cyan = rgba(a4fffff)
$bright_white = rgba(ffffffff)
