$bg = rgba(24282cff)
$fg = rgba(d8dee9ff)

$black = rgba(34383cff)
$red = rgba(e46c75ff)
$green = rgba(98c379ff)
$yellow = rgba(e0af68ff)
$blue = rgba(81a5ddff)
$magenta = rgba(c6a0f6ff)
$cyan = rgba(6cc6c8ff)
$white = rgba(d8dee9ff)

$bright_black = rgba(4c5054ff)
$bright_red = rgba(ed747fff)
$bright_green = rgba(a6d189ff)
$bright_yellow = rgba(e9b97aff)
$bright_blue = rgba(8db1ecff)
$bright_magenta = rgba(d2acffff)
$bright_cyan = rgba(79d2d4ff)
$bright_white = rgba(ebf1faff)
