$bg = rgba(282828ff)
$fg = rgba(ebdbb2ff)

$black = rgba(1d2021ff)
$red = rgba(cc241dff)
$green = rgba(98971aff)
$yellow = rgba(d79921ff)
$blue = rgba(458588ff)
$magenta = rgba(b16286ff)
$cyan = rgba(689d6aff)
$white = rgba(ebdbb2ff)

$bright_black = rgba(3c3836ff)
$bright_red = rgba(fb4934ff)
$bright_green = rgba(b8bb26ff)
$bright_yellow = rgba(fabd2fff)
$bright_blue = rgba(83a598ff)
$bright_magenta = rgba(d3869bff)
$bright_cyan = rgba(8ec07cff)
$bright_white = rgba(f9f5d7ff)
