$bg = rgba(2e3440ff)
$fg = rgba(eceff4ff)

$black = rgba(3b4252ff)
$red = rgba(bf616aff)
$green = rgba(a3be8cff)
$yellow = rgba(ebcb8bff)
$blue = rgba(81a1c1ff)
$magenta = rgba(b48eadff)
$cyan = rgba(88c0d0ff)
$white = rgba(e5e9f0ff)

$bright_black = rgba(4c566aff)
$bright_red = rgba(bf616aff)
$bright_green = rgba(a3be8cff)
$bright_yellow = rgba(ebcb8bff)
$bright_blue = rgba(81a1c1ff)
$bright_magenta = rgba(b48eadff)
$bright_cyan = rgba(8fbcbbff)
$bright_white = rgba(eceff4ff)
