$bg = rgba(171520ff)
$fg = rgba(ffffffff)

$black = rgba(1f212bff)
$red = rgba(fe4450ff)
$green = rgba(72f1b8ff)
$yellow = rgba(fede5dff)
$blue = rgba(03edf9ff)
$magenta = rgba(ff7edbff)
$cyan = rgba(36f9f6ff)
$white = rgba(ffffffff)

$bright_black = rgba(495495ff)
$bright_red = rgba(fa2e46ff)
$bright_green = rgba(09f7a0ff)
$bright_yellow = rgba(f3e70fff)
$bright_blue = rgba(2ee2faff)
$bright_magenta = rgba(a148abff)
$bright_cyan = rgba(03edf9ff)
$bright_white = rgba(b6b1b1ff)
