$bg = rgba(000000ff)
$fg = rgba(ffffffff)

$black = rgba(000000ff)
$red = rgba(555555ff)
$green = rgba(777777ff)
$yellow = rgba(999999ff)
$blue = rgba(bbbbbbbb)
$magenta = rgba(ddddddff)
$cyan = rgba(888888ff)
$white = rgba(ffffffff)

$bright_black = rgba(222222ff)
$bright_red = rgba(777777ff)
$bright_green = rgba(999999ff)
$bright_yellow = rgba(bbbbbbff)
$bright_blue = rgba(ddddddff)
$bright_magenta = rgba(f2f2f2ff)
$bright_cyan = rgba(ccccccff)
$bright_white = rgba(ffffffff)
