[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 75%"
max_size = "1920px 100%"
margin = 50
position = "15% 15%"
lazy = true

[scratchpads.bluetooth]
animation = "fromTop"
command = "kitty --class dropterm bluetuith"
class = "dropterm"
size = "50% 25%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.yazi]
animation = "fromTop"
command = "kitty --class yazi yazi"
class = "yazi"
size = "50% 70%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.spotify]
animation = "fromRight"
command = "spotify"
class = "Spotify"
size = "45% 90%"
max_size = "1920px 100%"
margin = 50
position = "55% 5%"
lazy = true

[scratchpads.whatsapp]
animation = "fromLeft"
command = "wasistlos"
class = "wasistlos"
size = "60% 80%"
max_size = "1920px 100%"
margin = 50
position = "0% 10%"
lazy = true
