[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 75%"
max_size = "1920px 100%"
margin = 50
position = "15% 15%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"

[scratchpads.bluetooth]
animation = "fromTop"
command = "kitty --class dropterm bluetuith"
class = "dropterm"
size = "50% 25%"
max_size = "1920px 100%"
margin = 50

[scratchpads.spotify]
animation = "fromLeft"
command = "spotify"
class = "spotify"
size = "50% 90%"
max_size = "1920px 100%"
margin = 50

[scratchpads.yazi]
animation = "fromTop"
command = "kitty --class yazi yazi"
class = "yazi"
size = "50% 70%"
max_size = "1920px 100%"
margin = 50

[scratchpads.whatsapp]
animation = "fromLeft"
command = "station"
class = "Station"
size = "90% 90%"
max_size = "1920px 100%"
margin = 10
