$mainMod = Alt

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Return, exec, kitty
bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, thunar
bind = $mainMod, F, fullscreen
bind = $mainMod SHIFT, F, togglefloating
bind = $mainMod SHIFT, M, exec, ~/.local/bin/switchlayout

bind = $mainMod, Space, exec, ~/.config/rofi/launchers/type-6/launcher.sh
bind = $mainMod, R, exec, ~/.config/rofi/launchers/type-6/runlauncher.sh
bind = $mainMod SHIFT ,W, exec, /home/adnanmalik/.config/rofi/launchers/type-6/windowlauncher.sh

bind = $mainMod, B, exec, firefox
bind = $mainMod, N, exec, ~/.local/bin/chwal
bind = $mainMod, C, exec, code
bind = $mainMod, O, exec, obsidian
bind = $mainMod, Z, exec, hyprpicker -a

# Change focus
bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, d

# Move Window
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d 

bind = $mainMod SHIFT, S, movetoworkspacesilent, special
bind = $mainMod, S, togglespecialworkspace

# pypr bindings
bind = $mainMod, T, exec, pypr toggle term
bind = $mainMod, U, exec, pypr toggle bluetooth
bind = $mainMod, Y, exec, pypr toggle yazi
bind = $mainMod, P, exec, pypr toggle spotify
bind = $mainMod, W, exec, pypr toggle whatsapp

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod CONTROL, l, resizeactive, 30 0
bind = $mainMod CONTROL, h, resizeactive, -30 0
bind = $mainMod CONTROL, k, resizeactive, 0 -30
bind = $mainMod CONTROL, j, resizeactive, 0 30

# Screenshot Bindings
bind = ,print,exec, hyprshot -m window -o ~/Pictures/Screenshots/ 
bind = SHIFT,print,exec, hyprshot -m region -o ~/Pictures/Screenshots/ 
bind = $mainMod,print,exec, hyprshot -m output -o ~/Pictures/Screenshots/ 


bind = ,INSERT,exec, hyprshot -m window -o ~/Pictures/Screenshots/ 
bind = SHIFT,INSERT,exec, hyprshot -m region -o ~/Pictures/Screenshots/ 
bind = $mainMod,INSERT,exec, hyprshot -m output -o ~/Pictures/Screenshots/ 

# Volume
bind = ,F6, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = ,F8, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = ,F7, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%

bind = , F3, exec, brightnessctl s +5%
bind = , F2, exec, brightnessctl s 5%-

bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
