# Setting Cursor Theme
env = HYPRCURSOR_SIZE,32
env = HYPRCURSOR_THEME capitaine-cursors-gruvbox
exec = hyprctl setcursor "Capitaine Cursors (Gruvbox)" 32

exec = gsettings set org.gnome.desktop.interface cursor-theme 'Capitaine Cursors (Gruvbox)'
exec = gsettings set org.gnome.desktop.interface cursor-size 32

# Fonts
exec = gsettings set org.gnome.desktop.interface font-name 'FiraCode Nerd Font Mono 10'
exec = gsettings set org.gnome.desktop.interface document-font-name 'FiraCode Nerd Font Mono 10'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'FiraCode Nerd Font Mono 9'
exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec = gsettings set org.gnome.desktop.interface font-hinting 'full'

#Icon, GTK and color scheme
exec = gsettings set org.gnome.desktop.interface icon-theme 'Gruvbox-Plus-Dark'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Gruvbox-Dark'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

