# Wallpapers
exec-once = swww-daemon
exec-once = swww img /home/adnanmalik/walls/catppuccin-walls/lofi.png

# Disk and Audio
exec-once = udiskie
exec-once = playerctld

# Idle Daemon
exec-once =  hypridle

# Authentication Agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Theming GTK
exec-once = ~/.local/bin/gtktheme

# Scratchpads
exec-once = /usr/bin/pypr

# Kde Connect
exec-once = kdeconnectd

# Fixing swaync
exec-once = pkill swaync

# Application Launcher
exec-once = vicinae server

# Launching waybar
exec-once = /home/adnanmalik/.config/waybar/scripts/launch.sh

# Software Remaps
exec-once = kanata -c /home/adnanmalik/.config/kanata/qwerty.kbd
