# Wallpapers
exec-once = swww-daemon
exec-once = swww img ~/walls/mainwalls/66.jpg

# Disk and Audio
exec-once = udiskie
exec-once = playerctld

# Idle Daemon
exec-once =  hypridle

# Polkit Agent
exec-once = systemctl --user start hyprpolkitagent

# Theming GTK
exec-once = ~/.local/bin/gtktheme

# Kde Connect
exec-once = kdeconnectd

# Fixing swaync
exec-once = pkill swaync

# Application Launcher
exec-once = vicinae server

# Launching waybar
exec-once = /home/adnanmalik/.local/bin/launchbar

# Software Remaps
exec-once = kanata -c /home/adnanmalik/.config/kanata/qwerty.kbd

# Low Battery Notification
exec-once = nohup /home/adnanmalik/.local/bin/battery_notify.sh

# Remove ly-session.log
exec-once = rm /home/adnanmalik/ly-session.log

# Clipboard
exec-once = wl-paste --type text --watch cliphist store

# BetterDiscord
exec-once = betterdiscordctl reinstall

# Spicetify
exec-once = spicetify backup apply

# Rclone
exec-once = rclone mount Gdrive: ~/Gdrive --vfs-cache-mode full
