# Wallpapers
exec-once = swww-daemon
exec-once = swww img /home/adnanmalik/walls/catppuccin-walls/abstract.png

# Disk and Audio
exec-once = udiskie
exec-once = playerctld

# Idle Daemon
exec-once =  hypridle

# Authentication Agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Theming GTK
exec-once = ~/.local/bin/gtktheme

# Scratchpads
exec-once = /usr/bin/pypr

# Kde Connect
exec-once = kdeconnectd

# Fixing swaync
exec-once = pkill swaync

# Launching waybar
exec-once = /home/adnanmalik/.config/waybar/scripts/launch.sh
