$mainMod = SUPER

# Main Keybindings
bind = $mainMod, Return, exec, ghostty
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen
bind = $mainMod, W, exec, $HOME/.local/bin/logoutblur.sh
bind = $mainMod SHIFT, F, togglefloating
bind = $mainMod SHIFT, W, exec, $HOME/.local/bin/launchbar

bind = $mainMod SHIFT, P, exec, toggle-kb-layout

bind = $mainMod, Space, exec,  ~/.config/rofi/launcher.sh
bind = $mainMod, E, exec, emoji.sh

bind = $mainMod, B, exec, firefox
bind = $mainMod, Z, exec, hyprpicker -a

# Change focus
bind = $mainMod, l, movefocus, r
bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = alt, space, exec, $(hyprctl activewindow -j | jq '.floating') && hyprctl dispatch cyclenext tiled || hyprctl dispatch cyclenext floating

# Move Window
bind = $mainMod CONTROL, H, movewindow, l
bind = $mainMod CONTROL, L, movewindow, r
bind = $mainMod CONTROL, K, movewindow, u
bind = $mainMod CONTROL, J, movewindow, d 


# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Resizing
bind = $mainMod SHIFT, l, resizeactive, 30 0
bind = $mainMod SHIFT, h, resizeactive, -30 0
bind = $mainMod SHIFT, k, resizeactive, 0 -30
bind = $mainMod SHIFT, j, resizeactive, 0 30

# Screenshot Bindings
bind = ,print,exec, hyprshot -m window -o ~/Pictures/Screenshots/ 
bind = SHIFT,print,exec, hyprshot -m region -o ~/Pictures/Screenshots/ 
bind = $mainMod,print,exec, hyprshot -m output -o ~/Pictures/Screenshots/ 

bind = ,INSERT,exec, hyprshot -m window -o ~/Pictures/Screenshots/ 
bind = SHIFT,INSERT,exec, hyprshot -m region -o ~/Pictures/Screenshots/ 
bind = $mainMod,INSERT,exec, hyprshot -m output -o ~/Pictures/Screenshots/ 

# Volume
bind = ,XF86AudioMute, exec, $HOME/.local/bin/volume.sh --toggle
bind = ,XF86AudioRaiseVolume, exec, $HOME/.local/bin/volume.sh --inc
bind = ,XF86AudioLowerVolume, exec, $HOME/.local/bin/volume.sh --dec

# Brightness
# bind = ,F3, exec, $HOME/.local/bin/brightness.sh --inc
# bind = ,F2, exec, $HOME/.local/bin/brightness.sh --dec

# Music Navigation
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# pypr bindings
bind = $mainMod, U, exec, pypr toggle bluetuith
bind = $mainMod, P, exec, pypr toggle spotify
bind = $mainMod, V, exec, pypr toggle proton
