# Setting Cursor Theme
exec = hyprctl setcursor "Catppuccin Mocha Dark" 24

env = GTK_THEME, Colloid-Purple-Dark-Catppuccin
env = XDG_CURRENT_DESKTOP,Hyprland
env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,24

exec-once = /opt/papirus-folders/papirus-folders -C cat-mocha-blue --theme Papirus-Dark
