windowrulev2 = float,class:^firefox$,title:^(Picture-in-Picture)
windowrulev2 = float,class:^zen$,title:^(Picture-in-Picture)
windowrulev2 = float,title:^(Sign in – Google accounts — Mozilla Firefox)
windowrulev2 = tile, class:^(Chromium)$, title:^(Kairu - Track your time like it matters)$
windowrulev2 = opacity 0.9 0.9,class:^(Thunar)$
layerrule = blur,vicinae
layerrule = ignorealpha 0, vicinae
