# Setting wallpaper
exec-once = swww-daemon

exec-once = /home/adnanmalik/.local/bin/chwal
# Setting up auto mounting
exec-once = udiskie

# Running the idle daemon
exec-once =  hypridle

# Running the polkit daemon
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Running the gtk theme
exec-once = ~/.local/bin/gtktheme

#Running pyprland
exec-once = /usr/bin/pypr

#Running kdeconnect daemon
exec-once = kdeconnectd

exec-once = pkill swaync

exec-once = /home/adnanmalik/.local/bin/launchbar

