exec-once = $HOME/clones/swww/target/release/swww-daemon
exec-once = /usr/bin/syncthing --no-browser
exec-once = /home/adnanmalik/.local/bin/chwal
exec-once = udiskie
exec-once = playerctld
exec-once =  hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ~/.local/bin/gtktheme
exec-once = /usr/bin/pypr
exec-once = kdeconnectd
exec-once = pkill swaync
exec-once = /home/adnanmalik/.local/bin/launchbar
exec-once = rclone mount eddy: ~/gdrive --vfs-cache-mode writes --daemon
exec-once = hyprpanel
