# Setting Cursor Theme
env = HYPRCURSOR_SIZE,28
env = HYPRCURSOR_THEME capitaine-cursors-gruvbox
exec = hyprctl setcursor capitaine-cursors-gruvbox 28
exec = gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors-gruvbox'
exec = gsettings set org.gnome.desktop.interface cursor-size 28

# Fonts
exec = gsettings set org.gnome.desktop.interface font-name 'FiraCode Nerd Font Mono 10'
exec = gsettings set org.gnome.desktop.interface document-font-name 'FiraCode Nerd Font Mono 10'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'FiraCode Nerd Font Mono 9'
exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec = gsettings set org.gnome.desktop.interface font-hinting 'full'

#Icon, GTK and color scheme
exec = gsettings set org.gnome.desktop.interface icon-theme 'Gruvbox-Plus-Dark'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Gruvbox-Retro'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

