exec-once = swww-daemon
exec-once = swww img /home/adnanmalik/walls/catppuccin-walls/anime_skyline.png
exec-once = /usr/bin/syncthing --no-browser
exec-once = udiskie
exec-once = playerctld
exec-once =  hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ~/.local/bin/gtktheme
exec-once = /usr/bin/pypr
exec-once = kdeconnectd
exec-once = pkill swaync
exec-once = /home/adnanmalik/.config/waybar/scripts/launch.sh
exec-once = rclone mount eddy: ~/gdrive --vfs-cache-mode writes --daemon
