monitor = ,1920x1080,auto, 1

ecosystem{
  no_update_news = true
}


general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(83a59890)
    col.inactive_border = rgba(92837480)
    layout = dwindle
    allow_tearing = false
}

