#!/bin/bash

bookmark="$(xclip -o -selected primary)"
file="$HOME/notes.txt"

if grep -q "^$bookmark$" "$file";then
	notify-send "Oops!" "Already bookmarked!"
else
	notify-send "Bookmark added!" "$bookmark is now saved"
	echo "$bookmark">> "$file"
fi
