#!/bin/bash

wal -q -i ~/wallpaper/

wallpaper_path=$(cat "$HOME/.cache/wal/wal")

swww img $wallpaper_path

cd $HOME/.config/waybar/
./launch.sh
cd $HOME/.dotfiles/scripts/ 
./wal-telegram
./chalac
./chchrome
./wal-zathura
./wal-discord
./wallpaper_history
cp $wallpaper_path ~/.cache/wal/default.jpg

notify-send $(basename $wallpaper_path)
