#!/home/adnanmalik/.local/share/pipx/venvs/kanban-tui/bin/python
import sys
from kanban_tui.__main__ import cli
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(cli())
