#!/bin/sh

# Kill existing waybar
pkill waybar

# Give it a moment to exit
sleep 0.5

# Restart waybar in background
waybar --config $HOME/.config/waybar/current/config.jsonc -s $HOME/.config/waybar/current/style.css &
