#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Log Out\n  Lock" | rofi -dmenu) 

case "$chosen" in
	"  Power Off") shutdown now ;;
	"  Restart") shutdown -r now;;
	"  Log Out") logout ;;
	"  Lock") lock ;;
	*) exit 1 ;;
esac
