#!/bin/bash

# Function to rename files in a folder
rename_files() {
  local dir="$1"
  
  # Find all files (not directories) in this folder
  find "$dir" -maxdepth 1 -type f | while read -r f; do
    filename=$(basename "$f")
    
    # Check if filename starts with a number followed by dot and space
    if [[ "$filename" =~ ^([0-9]+)\.\ (.*) ]]; then
      num=${BASH_REMATCH[1]}
      name=${BASH_REMATCH[2]}
      
      # Pad number with leading zero if less than 10
      printf -v newnum "%02d" "$num"
      
      # Rename the file
      mv "$f" "$dir/$newnum. $name"
      echo "Renamed '$f' -> '$dir/$newnum. $name'"
    fi
  done

  # Recursively go into subdirectories
  for subdir in "$dir"/*/; do
    [ -d "$subdir" ] && rename_files "$subdir"
  done
}

# Start from current directory
rename_files "."
