#!/bin/bash

TERMINAL="ghostty"
BROWSER="firefox"
NOTES="notion-app"


hyprctl dispatch workspace 1
$TERMINAL &
sleep 2
hyprctl dispatch workspace 2
$BROWSER &
sleep 3

hyprctl dispatch workspace 3
$NOTES &
sleep 3

hyprctl dispatch workspace 1
