require("plugins.setup")
require("plugins.ui")
require("plugins.mini")
require("plugins.conform")
-- require("nvim.lua.plugins.treesitter_old")
require("plugins.lualine")
-- require("plugins.heirline")
require("plugins.treesitter")
-- require("plugins.render-markdown")
-- require("plugins.nvim-ts-autotag")
require("plugins.lorem")
require("plugins.markdown")
require("plugins.theme")
require("plugins.completion")
require("plugins.lint")
require("plugins.lsp")
require("plugins.snacks")
require("plugins.bufferline")
require("plugins.tabout")
-- require("plugins.obsidian")
