$bg = rgba(0f1419ff)
$fg = rgba(bfbdb6ff)

$black = rgba(000000ff)
$red = rgba(f07178ff)
$green = rgba(b8cc52ff)
$yellow = rgba(e6b450ff)
$blue = rgba(59c2ffff)
$magenta = rgba(d2a6ffff)
$cyan = rgba(95e6cbff)
$white = rgba(bfbdb6ff)

$bright_black = rgba(323232ff)
$bright_red = rgba(f07178ff)
$bright_green = rgba(b8cc52ff)
$bright_yellow = rgba(e6b450ff)
$bright_blue = rgba(59c2ffff)
$bright_magenta = rgba(d2a6ffff)
$bright_cyan = rgba(95e6cbff)
$bright_white = rgba(ffffffff)
