$bg = rgba(1e1e2eff)
$fg = rgba(cdd6f4ff)

$black = rgba(181825ff)
$red = rgba(f38ba8ff)
$green = rgba(a6e3a1ff)
$yellow = rgba(f9e2afff)
$blue = rgba(89b4faff)
$magenta = rgba(cba6f7ff)
$cyan = rgba(94e2d5ff)
$white = rgba(cdd6f4ff)

$bright_black = rgba(6c7086ff)
$bright_red = rgba(f38ba8ff)
$bright_green = rgba(a6e3a1ff)
$bright_yellow = rgba(f9e2afff)
$bright_blue = rgba(89b4faff)
$bright_magenta = rgba(cba6f7ff)
$bright_cyan = rgba(94e2d5ff)
$bright_white = rgba(ebe9faff)
