$bg = rgba(1c1c1cff)
$fg = rgba(e6e6e6ff)

$black = rgba(2a2a2aff)
$red = rgba(d8b4b4ff)
$green = rgba(c4d6c4ff)
$yellow = rgba(ded8b8ff)
$blue = rgba(c3caddff)
$magenta = rgba(dac3ddff)
$cyan = rgba(c3deddff)
$white = rgba(f2f2f2ff)

$bright_black = rgba(4a4a4aff)
$bright_red = rgba(e8c8c8ff)
$bright_green = rgba(d8e6d8ff)
$bright_yellow = rgba(eeeac9ff)
$bright_blue = rgba(d5daf1ff)
$bright_magenta = rgba(e8d5f1ff)
$bright_cyan = rgba(d5f0f0ff)
$bright_white = rgba(ffffffff)
