# ZSH Configuration

source "$HOME/dotfiles/zsh/env.zsh"
source "$HOME/dotfiles/zsh/plugins.zsh"
source "$HOME/dotfiles/zsh/bindings.zsh"
source "$HOME/dotfiles/zsh/completion.zsh"
source "$HOME/dotfiles/zsh/prompt.zsh"
source "$HOME/dotfiles/zsh/options.zsh"
source "$HOME/dotfiles/zsh/history.zsh"
source "$HOME/dotfiles/zsh/fzf.zsh"
source "$HOME/dotfiles/zsh/tools.zsh"
source "$HOME/dotfiles/zsh/aliases.zsh"
source "$HOME/dotfiles/zsh/functions.zsh"

if [[ -f "$HOME/dotfiles/zsh/local.zsh" ]]; then
  source "$HOME/dotfiles/zsh/local.zsh"
fi
