# The basic colors
foreground              #d6d6d6
background              #101010
selection_foreground    #101010
selection_background    #d6d6d6

# Cursor colors
cursor                  #cccccc
cursor_text_color       #101010

# URL underline color
url_color               #b4b4b4

# Borders
active_border_color     #9e9e9e
inactive_border_color   #5b5b5b
bell_border_color       #a8a8a8

# Tabs
active_tab_foreground   #101010
active_tab_background   #b4b4b4
inactive_tab_foreground #a0a0a0
inactive_tab_background #191919
tab_bar_background      #101010

# Marks
mark1_foreground #101010
mark1_background #bcbcbc
mark2_foreground #101010
mark2_background #b9b9b9
mark3_foreground #101010
mark3_background #c3c3c3


##########################################
# Purely monochromatic 16 terminal colors
# Black, white, and neutral greys only
##########################################

# black
color0  #111111
color8  #3a3a3a

# red
color1  #a8a8a8
color9  #c0c0c0

# green
color2  #adadad
color10 #bdbdbd

# yellow
color3  #b8b8b8
color11 #cecece

# blue
color4  #a2a2a2
color12 #b5b5b5

# magenta
color5  #b0b0b0
color13 #c6c6c6

# cyan
color6  #ababab
color14 #bcbcbc

# white
color7  #c7c7c7
color15 #e0e0e0
