# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #ffffff
background              #171520
selection_foreground    #1f212b
selection_background    #ffffff

# Cursor colors
cursor                  #f97e72
cursor_text_color       #171520

# URL underline color when hovering with mouse
url_color               #f24450

# Kitty window border colors
active_border_color     #03edf9
inactive_border_color   #b6b1b1
bell_border_color       #fede5d

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #171520
active_tab_background   #ff7edb
inactive_tab_foreground #ffffff
inactive_tab_background #1f212b
tab_bar_background      #232530

# Colors for marks (marked text in the terminal)
mark1_foreground #171520
mark1_background #495495
mark2_foreground #171520
mark2_background #a148ab
mark3_foreground #232530
mark3_background #2ee2fa

# The 16 terminal colors

# black
color0 #171529
color8 #232530

# red
color1 #fe4450
color9 #fa2e46

# green
color2  #72fab8
color10 #09f7a0

# yellow
color3  #fede5d
color11 #f3e70f

# blue
color4  #03edf9
color12 #2ee2fa

# magenta
color5  #ff7edb
color13 #a148ab

# cyan
color6  #36f9f6
color14 #03edf9

# white
color7  #ffffff
color15 #d6d6d6
