windowrule = float on, match:class ^firefox$, match:title ^(Picture-in-Picture)
windowrule = float on, match:class ^zen$, match:title ^(Picture-in-Picture)
windowrule = float on, match:title ^(Sign in – Google accounts — Mozilla Firefox)
windowrule = tile on, match:class ^(Chromium)$, match:title ^(Kairu - Track your time like it matters)$
windowrule = opacity 0.9 0.9, match:class ^(Thunar)$
# layerrule = blur,vicinae
# layerrule = ignorealpha 0, vicinae
windowrule = tile on, match:class ^(Thorium-browser)

windowrule {
  name = windowrule-1
  float = on
  match:class = ^(launcher)$
}

windowrule {
  name = windowrule-2
  size = 800 500
  center = on
  match:class = ^(launcher)$
}

